"""
Graph state definition.
"""
from typing import TypedDict, Dict, Any, List, Optional

class State(TypedDict):
    """
    Definition of the state used in the flow graph of the QA system with feedback.
    """
    question: str                    # Current question
    llm_response: str                # Response generated by the LLM
    human_feedback: str              # Human feedback (validated/rejected)
    is_validated: bool               # If the response was validated
    previous_responses: List[str]    # List of previous responses
    feedback_notes: str              # Additional feedback notes
    from_database: bool              # If the response came from the database
    adapted_response: str            # Adapted response (if applicable)
    original_question: str           # Original question (if adapted)
    is_identical: bool               # If it's a question identical to an existing one

# Exports the class so it can be imported from other modules
__all__ = ['State']